apiVersion: v1
kind: Service
metadata:
  name: logging-server
spec:
  type: NodePort
  ports:
  - port: 80
  selector:
    app: logging-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: logging-server
  labels:
    app: logging-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logging-server
  template:
    metadata:
      labels:
        app: logging-server
    spec:
      containers:
      - name: logging-server
        image: localhost:5000/loggingimage:1.0
        ports:
        - containerPort: 80